# Generated by Django 3.0.4 on 2020-03-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='younger_age_band',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
