# Generated by Django 3.0.4 on 2020-03-10 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_younger_age_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Clinician'),
        ),
    ]
