# Generated by Django 3.0.4 on 2020-03-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient_clinician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
    ]
