# Generated by Django 3.0.4 on 2020-03-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200310_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='clinician',
            new_name='clinician_id',
        ),
    ]
