# Generated by Django 3.0.4 on 2020-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200317_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='haptic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='text_to_speech',
            field=models.BooleanField(default=True),
        ),
    ]
