# Generated by Django 3.0.4 on 2020-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200321_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='part_1_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='part_2_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
