# Generated by Django 3.0.4 on 2020-04-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200413_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='part_1_attempt_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='part_2_attempt_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
