# Generated by Django 3.0.4 on 2020-04-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200413_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='current_attempt_number',
            field=models.IntegerField(default=1),
        ),
    ]
