# Generated by Django 3.0.4 on 2020-04-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200401_0935'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='survey',
            new_name='survey_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='patient',
            new_name='patient_id',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='responsekey',
            old_name='survey',
            new_name='survey_id',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_number', 'survey_id')},
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question_id', 'patient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='responsekey',
            unique_together={('survey_id', 'response')},
        ),
    ]
