# Generated by Django 3.0.4 on 2020-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200413_1019'),
        ('survey', '0002_auto_20200401_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='attempt_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question_id', 'patient_id', 'attempt_number')},
        ),
    ]
