# Generated by Django 3.0.4 on 2020-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200413_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
