# Generated by Django 3.0.4 on 2020-03-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200320_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_number', 'question', 'survey')},
        ),
    ]
