# Generated by Django 3.0.4 on 2020-03-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200320_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_number', 'survey')},
        ),
    ]
