# Generated by Django 3.0.4 on 2020-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20200320_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsekey',
            name='response_key',
            field=models.CharField(choices=[('NT', 'NOT AT ALL TRUE'), ('LT', 'A LITTLE BIT TRUE'), ('MT', 'MOSTLY TRUE'), ('CT', 'COMPLETELY TRUE'), ('VD', 'VERY DIFFICULT'), ('D', 'DIFFICULT'), ('E', 'EASY'), ('VE', 'VERY EASY')], max_length=2),
        ),
    ]
