# Generated by Django 3.0.4 on 2020-03-21 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200321_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
